[project]
name = "cit_message_board"
version = "0.1.1"
description = "A place where members of the CIT can share messages, events, and personal projects"
dependencies = [
    "flask"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"