DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS post;

CREATE TABLE admin (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    admin_id INTEGER,
    created TEXT NOT NULL,
    begins TEXT NOT NULL,
    expires TEXT NOT NULL,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    data BLOB NOT NULL
);